### ISSUE TITLE
release missing

### ISSUE THREAD

**Issue by 9il** [economicmodeling/libddoc#2]
Please create initial release with tag like `v0.0`. This is needed for `code.dlang.org`.

**Comment by MartinNowak** [comment]
Any update on this? Quite a few downstream libraries depend on libddoc.

**Comment by Hackerpilot** [comment]
I just tagged 0.1.0 with whatever happened to be in master at the time.

**Comment by MartinNowak** [comment]
Thanks Brian, have you already added it to code.dlang.org?

**Comment by Hackerpilot** [comment]
I just did
