### ISSUE TITLE
parseComment gets stuck with certain input(s?)

### ISSUE THREAD

**Issue by kiith-sa** [economicmodeling/libddoc#21]
The following code gets stuck in parseComment (with current libddoc ~master):

```
import std.stdio;
import ddoc.comments;


void main()
{
        writeln("Before");
        Comment TEST = parseComment(
        "\n"
        "Params:\n"
        "    dg = \n", null);
        writeln("After");
}
```

Not sure what is the reason, but when I remove the space between `dg =` and the newline, it runs normally. Noticed this when trying to build docs for the `mambo` project at code.dlang.org.

**Comment by Hackerpilot** [comment]
Is that the content of a \`\` or `---` style code example?

**Comment by kiith-sa** [comment]
no, that `parseComment()` call, when passed that string, gets stuck.

**Comment by Geod24** [comment]
My money is on this:
https://github.com/economicmodeling/libddoc/blob/40e5ec3256a7e17bbcde2048b7b1f8afcd50d8d5/src/ddoc/macros.d#L410
